import type { BotSchematic, BotSchematicType } from "./types";

export const BOT_SCHEMATICS: Record<BotSchematicType, BotSchematic> = {
  arbitrage: {
    type: "arbitrage",
    name: "Arbitrage",
    icon: "⚡",
    description: "Cross-DEX price discrepancy scanner & executor",
    dockerImage: "cryptodev/bot-arbitrage:latest",
    envTemplate: {
      SOURCE_DEX: "",
      TARGET_DEX: "",
      TOKEN_PAIR: "",
      MIN_PROFIT_PCT: "0.5",
    },
    questions: [
      {
        id: "source-dex",
        label: "Source DEX",
        type: "select",
        options: ["Uniswap V3", "SushiSwap", "PancakeSwap"],
        required: true,
        envKey: "SOURCE_DEX",
        placeholder: "Select source exchange",
      },
      {
        id: "target-dex",
        label: "Target DEX",
        type: "select",
        options: ["Uniswap V3", "SushiSwap", "PancakeSwap"],
        required: true,
        envKey: "TARGET_DEX",
        placeholder: "Select target exchange",
      },
      {
        id: "token-pair",
        label: "Token Pair",
        type: "text",
        required: true,
        envKey: "TOKEN_PAIR",
        placeholder: "e.g. WETH/USDC",
      },
      {
        id: "min-profit",
        label: "Min Profit %",
        type: "number",
        required: true,
        envKey: "MIN_PROFIT_PCT",
        placeholder: "0.5",
        defaultValue: 0.5,
      },
    ],
  },

  signal: {
    type: "signal",
    name: "Signal Bot",
    icon: "📡",
    description: "Monitor wallets & emit webhook alerts on activity",
    dockerImage: "cryptodev/bot-signal:latest",
    envTemplate: {
      WATCH_ADDRESSES: "",
      WEBHOOK_URL: "",
      ALERT_THRESHOLD: "1000",
    },
    questions: [
      {
        id: "watch-addresses",
        label: "Watch Addresses",
        type: "text",
        required: true,
        envKey: "WATCH_ADDRESSES",
        placeholder: "0xabc…, 0xdef… (comma-separated)",
      },
      {
        id: "webhook-url",
        label: "Webhook URL",
        type: "text",
        required: true,
        envKey: "WEBHOOK_URL",
        placeholder: "https://hooks.example.com/…",
      },
      {
        id: "alert-threshold",
        label: "Alert Threshold (USD)",
        type: "number",
        required: true,
        envKey: "ALERT_THRESHOLD",
        placeholder: "1000",
        defaultValue: 1000,
      },
    ],
  },

  mev: {
    type: "mev",
    name: "MEV Bot",
    icon: "🔥",
    description: "Sandwich, backrun & frontrun strategy executor",
    dockerImage: "cryptodev/bot-mev:latest",
    envTemplate: {
      STRATEGY: "",
      GAS_LIMIT: "500000",
      TARGET_PAIRS: "",
    },
    questions: [
      {
        id: "strategy",
        label: "Strategy",
        type: "select",
        options: ["sandwich", "backrun", "frontrun"],
        required: true,
        envKey: "STRATEGY",
        placeholder: "Select MEV strategy",
      },
      {
        id: "gas-limit",
        label: "Gas Limit",
        type: "number",
        required: true,
        envKey: "GAS_LIMIT",
        placeholder: "500000",
        defaultValue: 500000,
      },
      {
        id: "target-pairs",
        label: "Target Pairs",
        type: "text",
        required: true,
        envKey: "TARGET_PAIRS",
        placeholder: "WETH/USDC, WETH/DAI",
      },
    ],
  },

  scraper: {
    type: "scraper",
    name: "Data Scraper",
    icon: "🕷️",
    description: "On-chain data extraction & indexing pipeline",
    dockerImage: "cryptodev/bot-scraper:latest",
    envTemplate: {
      DATA_SOURCE: "",
      SCRAPE_INTERVAL: "60",
    },
    questions: [
      {
        id: "data-source",
        label: "Data Source",
        type: "select",
        options: ["etherscan", "dune", "debank"],
        required: true,
        envKey: "DATA_SOURCE",
        placeholder: "Select data source",
      },
      {
        id: "scrape-interval",
        label: "Scrape Interval (seconds)",
        type: "number",
        required: true,
        envKey: "SCRAPE_INTERVAL",
        placeholder: "60",
        defaultValue: 60,
      },
    ],
  },

  social: {
    type: "social",
    name: "Social Bot",
    icon: "💬",
    description: "Monitor & interact on decentralized social platforms",
    dockerImage: "cryptodev/bot-social:latest",
    envTemplate: {
      PLATFORM: "",
      KEYWORDS: "",
    },
    questions: [
      {
        id: "platform",
        label: "Platform",
        type: "select",
        options: ["farcaster", "lens", "twitter"],
        required: true,
        envKey: "PLATFORM",
        placeholder: "Select social platform",
      },
      {
        id: "keywords",
        label: "Keywords",
        type: "text",
        required: true,
        envKey: "KEYWORDS",
        placeholder: "defi, airdrop, alpha",
      },
    ],
  },

  "ai-chat": {
    type: "ai-chat",
    name: "AI Chat Agent",
    icon: "🤖",
    description: "LLM-powered conversational trading assistant",
    dockerImage: "cryptodev/bot-ai-chat:latest",
    envTemplate: {
      MODEL: "",
      SYSTEM_PROMPT: "",
    },
    questions: [
      {
        id: "model",
        label: "Model",
        type: "select",
        options: ["gpt-4", "claude", "llama"],
        required: true,
        envKey: "MODEL",
        placeholder: "Select LLM model",
      },
      {
        id: "system-prompt",
        label: "System Prompt",
        type: "text",
        required: true,
        envKey: "SYSTEM_PROMPT",
        placeholder: "You are a DeFi trading assistant…",
      },
    ],
  },

  sniper: {
    type: "sniper",
    name: "Token Sniper",
    icon: "🎯",
    description: "Snipe new token launches & liquidity additions",
    dockerImage: "cryptodev/bot-sniper:latest",
    envTemplate: {
      TARGET_TOKEN: "",
      DEX_ROUTER: "",
      MAX_BUY_USD: "1000",
      GAS_PRIORITY: "high",
      SLIPPAGE_PCT: "5",
    },
    questions: [
      {
        id: "target-token",
        label: "Target Token",
        type: "text",
        required: true,
        envKey: "TARGET_TOKEN",
        placeholder: "Token address or symbol",
      },
      {
        id: "dex-router",
        label: "DEX Router",
        type: "select",
        options: ["Uniswap V3", "PancakeSwap", "SushiSwap"],
        required: true,
        envKey: "DEX_ROUTER",
        placeholder: "Select DEX router",
      },
      {
        id: "max-buy",
        label: "Max Buy Amount (USD)",
        type: "number",
        required: true,
        envKey: "MAX_BUY_USD",
        placeholder: "1000",
        defaultValue: 1000,
      },
      {
        id: "gas-priority",
        label: "Gas Priority",
        type: "select",
        options: ["low", "medium", "high", "ultra"],
        required: true,
        envKey: "GAS_PRIORITY",
        placeholder: "Select gas priority",
      },
      {
        id: "slippage",
        label: "Slippage %",
        type: "number",
        required: true,
        envKey: "SLIPPAGE_PCT",
        placeholder: "5",
        defaultValue: 5,
      },
    ],
  },

  liquidation: {
    type: "liquidation",
    name: "Liquidation Bot",
    icon: "💀",
    description: "Monitor & execute DeFi liquidations on lending protocols",
    dockerImage: "cryptodev/bot-liquidation:latest",
    envTemplate: {
      PROTOCOL: "",
      MIN_PROFIT_USD: "50",
      HEALTH_FACTOR_THRESHOLD: "1.05",
      MAX_GAS: "800000",
    },
    questions: [
      {
        id: "protocol",
        label: "Protocol",
        type: "select",
        options: ["Aave V3", "Compound V3", "MakerDAO", "Morpho"],
        required: true,
        envKey: "PROTOCOL",
        placeholder: "Select lending protocol",
      },
      {
        id: "min-profit",
        label: "Min Profit (USD)",
        type: "number",
        required: true,
        envKey: "MIN_PROFIT_USD",
        placeholder: "50",
        defaultValue: 50,
      },
      {
        id: "health-factor",
        label: "Health Factor Threshold",
        type: "number",
        required: true,
        envKey: "HEALTH_FACTOR_THRESHOLD",
        placeholder: "1.05",
        defaultValue: 1.05,
      },
      {
        id: "max-gas",
        label: "Max Gas",
        type: "number",
        required: true,
        envKey: "MAX_GAS",
        placeholder: "800000",
        defaultValue: 800000,
      },
    ],
  },

  "copy-trade": {
    type: "copy-trade",
    name: "Copy Trader",
    icon: "🔄",
    description: "Mirror trades from whale wallets in real-time",
    dockerImage: "cryptodev/bot-copy-trade:latest",
    envTemplate: {
      TARGET_WALLETS: "",
      COPY_PERCENTAGE: "100",
      MIN_TRADE_USD: "100",
      MAX_TRADE_USD: "10000",
      EXCLUDE_TOKENS: "",
    },
    questions: [
      {
        id: "target-wallets",
        label: "Target Wallets",
        type: "text",
        required: true,
        envKey: "TARGET_WALLETS",
        placeholder: "0xabc…, 0xdef… (comma-separated addresses)",
      },
      {
        id: "copy-percentage",
        label: "Copy Percentage",
        type: "number",
        required: true,
        envKey: "COPY_PERCENTAGE",
        placeholder: "100",
        defaultValue: 100,
      },
      {
        id: "min-trade",
        label: "Min Trade (USD)",
        type: "number",
        required: true,
        envKey: "MIN_TRADE_USD",
        placeholder: "100",
        defaultValue: 100,
      },
      {
        id: "max-trade",
        label: "Max Trade (USD)",
        type: "number",
        required: true,
        envKey: "MAX_TRADE_USD",
        placeholder: "10000",
        defaultValue: 10000,
      },
      {
        id: "exclude-tokens",
        label: "Exclude Tokens",
        type: "text",
        required: false,
        envKey: "EXCLUDE_TOKENS",
        placeholder: "SHIB, DOGE (optional, comma-separated)",
      },
    ],
  },

  rebalancer: {
    type: "rebalancer",
    name: "Portfolio Rebalancer",
    icon: "⚖️",
    description: "Auto-rebalance portfolio allocations on schedule",
    dockerImage: "cryptodev/bot-rebalancer:latest",
    envTemplate: {
      TARGET_ALLOCATIONS: "",
      REBALANCE_THRESHOLD_PCT: "5",
      FREQUENCY: "daily",
      MAX_SLIPPAGE_PCT: "1",
    },
    questions: [
      {
        id: "target-allocations",
        label: "Target Allocations",
        type: "text",
        required: true,
        envKey: "TARGET_ALLOCATIONS",
        placeholder: "ETH:40,BTC:30,USDC:30",
      },
      {
        id: "rebalance-threshold",
        label: "Rebalance Threshold %",
        type: "number",
        required: true,
        envKey: "REBALANCE_THRESHOLD_PCT",
        placeholder: "5",
        defaultValue: 5,
      },
      {
        id: "frequency",
        label: "Frequency",
        type: "select",
        options: ["hourly", "daily", "weekly"],
        required: true,
        envKey: "FREQUENCY",
        placeholder: "Select rebalance frequency",
      },
      {
        id: "max-slippage",
        label: "Max Slippage %",
        type: "number",
        required: true,
        envKey: "MAX_SLIPPAGE_PCT",
        placeholder: "1",
        defaultValue: 1,
      },
    ],
  },
};
